import os
import re
import time
import random
import requests
from flask import render_template, request, redirect, url_for, session, flash, jsonify, current_app

from client.blueprint import client_bp
from client.decorators import login_required, verify_peer_access
from models import Client
from services.netbird_service import (
    get_cached_all_netbird_peers,
    get_cached_peer_vpn_only,
    check_single_peer_handshake,
    get_api_base_url,
    get_api_headers
)
from utils.cache_manager import (
    firewall_cache_lock,
    firewall_rules_cache,
    get_name_override
)
from utils.network_validators import validate_address_spec, validate_port_spec


@client_bp.route('/peers/<peer_id>/firewall')
@login_required
def peer_firewall(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    
    if not customer or not verify_peer_access(customer, peer_id):
        flash("Unauthorized access to this device.", "error")
        return redirect(url_for('client.dashboard'))

    is_online = False
    peer_name = 'Edge Device'
    
    override_name = get_name_override(peer_id)
    if override_name:
        peer_name = override_name

    vpn_only = False
    try:
        base_url = get_api_base_url()
        headers = get_api_headers()
        peers_data = get_cached_all_netbird_peers(base_url, headers, cache_ttl=10)
        peer_data = next((p for p in peers_data if p.get("id") == peer_id), None)
        if peer_data:
            checked_peer = check_single_peer_handshake(peer_data, base_url, headers)
            is_online = checked_peer.get("is_online", False)
            if not override_name and checked_peer.get('name'):
                peer_name = checked_peer.get('name')
            if peer_data.get("ip"):
                vpn_only = get_cached_peer_vpn_only(peer_id, peer_data.get("ip"))
    except Exception as e:
        current_app.logger.error(f"Error checking peer status on loading firewall page: {e}")

    if not is_online:
        return redirect(url_for('client.peer_details', peer_id=peer_id))

    return render_template(
        'firewall.html',
        peer_id=peer_id,
        peer_name=peer_name,
        customer_name=session.get('client_customer_name'),
        is_online=is_online,
        vpn_only=vpn_only
    )


@client_bp.route('/api/peers/<peer_id>/firewall/rules', methods=['GET'])
@login_required
def get_peer_firewall_rules(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"rules": [], "agent_online": False}), 200

    peer_ip = peer.get("ip")
    
    now = time.time()
    cached_live_rules = []
    agent_online = False
    cache_found = False
    cache_time = 0

    with firewall_cache_lock:
        if peer_id in firewall_rules_cache:
            cached_live_rules, agent_online, cache_time = firewall_rules_cache[peer_id]
            cache_found = True

    force_refresh = request.args.get('refresh', 'false').lower() == 'true'
    should_revalidate = force_refresh or not cache_found or (now - cache_time > 15)
    
    if should_revalidate:
        try:
            url = f"http://{peer_ip}:8765/firewall/rules"
            resp = requests.get(url, timeout=5)
            if resp.ok:
                agent_online = True
                cached_live_rules = resp.json().get("rules", [])
            
            with firewall_cache_lock:
                firewall_rules_cache[peer_id] = (cached_live_rules, agent_online, time.time())
        except Exception as e:
            current_app.logger.error(f"Sync firewall rules fetch failed: {e}")

    rules_data = []
    for idx, lr in enumerate(cached_live_rules):
        src_ips = []
        for s in (lr.get("src") or []):
            if s.startswith('@alias_'):
                s = '@' + s[7:]
            src_ips.append(s)
        src_ip = ",".join(src_ips) if src_ips else "Any"

        dst_ips = []
        for d in (lr.get("dst") or []):
            if d.startswith('@alias_'):
                d = '@' + d[7:]
            dst_ips.append(d)
        dst_ip = ",".join(dst_ips) if dst_ips else "Any"

        comment = lr.get("comment", "")
        is_autogenerated = bool(re.match(r"^rule_\d{6}$", comment))
        ui_name = "" if is_autogenerated else comment

        action = lr.get("action", "DROP")
        if action.lower() in ("accept", "allow"):
            action = "ALLOW"
        else:
            action = "DROP"

        src_ports = lr.get("src_port")
        if isinstance(src_ports, list):
            src_port = ",".join(src_ports)
        else:
            src_port = src_ports or ""

        dst_ports = lr.get("dst_port")
        if isinstance(dst_ports, list):
            dst_port = ",".join(dst_ports)
        else:
            dst_port = dst_ports or ""

        rules_data.append({
            "id": idx + 1,
            "rule_name": ui_name,
            "src_ip": src_ip,
            "dst_ip": dst_ip,
            "src_port": src_port,
            "dst_port": dst_port,
            "protocol": lr.get("protocol") or "any",
            "action": action,
            "interface": lr.get("interface") or "lan",
            "enabled": lr.get("enabled", True),
            "active_on_agent": True,
            "direction": lr.get("id"),
            "order": lr.get("order", idx + 1),
            "packets": lr.get("packets"),
            "bytes": lr.get("bytes")
        })

    return jsonify({
        "rules": rules_data,
        "agent_online": agent_online
    }), 200


@client_bp.route('/api/peers/<peer_id>/firewall/rules', methods=['POST'])
@login_required
def add_peer_firewall_rule(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    req_data = request.get_json() or {}
    rule_name = req_data.get('rule_name')
    rule_name = rule_name.strip() if rule_name else ''
    
    action = req_data.get('action')
    action = action.lower() if action else 'drop'
    if action == 'accept':
        action = 'allow'
    
    protocol = req_data.get('protocol')
    protocol = protocol.lower() if protocol else 'any'

    interface = req_data.get('interface')
    interface = interface.lower() if interface else 'lan'

    src_ip = req_data.get('src_ip')
    src_ip = src_ip.strip() if (src_ip and isinstance(src_ip, str)) else None

    dst_ip = req_data.get('dst_ip')
    dst_ip = dst_ip.strip() if (dst_ip and isinstance(dst_ip, str)) else None

    src_port = req_data.get('src_port')
    src_port = src_port.strip() if (src_port and isinstance(src_port, str)) else None

    dst_port = req_data.get('dst_port')
    dst_port = dst_port.strip() if (dst_port and isinstance(dst_port, str)) else None

    order = req_data.get('order')

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        live_rules = live_resp.json().get("rules", []) if live_resp.ok else []
    except Exception:
        live_rules = []

    if not rule_name:
        rule_name = f"rule_{random.randint(100000, 999999)}"
        while any(lr.get("comment") == rule_name for lr in live_rules):
            rule_name = f"rule_{random.randint(100000, 999999)}"

    if action not in ('allow', 'drop'):
        return jsonify({"error": "Action must be 'allow' or 'drop'"}), 400

    if protocol not in ('tcp', 'udp', 'tcp+udp', 'icmp', 'any'):
        return jsonify({"error": "Protocol must be 'tcp', 'udp', 'tcp+udp', 'icmp', or 'any'"}), 400

    if interface not in ('lan', 'vpn'):
        return jsonify({"error": "Interface must be 'lan' or 'vpn'"}), 400

    try:
        src_parts = validate_address_spec(src_ip)
    except ValueError as e:
        return jsonify({"error": f"Source Address Error: {str(e)}"}), 400

    try:
        dst_parts = validate_address_spec(dst_ip)
    except ValueError as e:
        return jsonify({"error": f"Destination Address Error: {str(e)}"}), 400

    try:
        src_port_parts = validate_port_spec(src_port)
    except ValueError as e:
        return jsonify({"error": f"Source Port Error: {str(e)}"}), 400

    try:
        dst_port_parts = validate_port_spec(dst_port)
    except ValueError as e:
        return jsonify({"error": f"Destination Port Error: {str(e)}"}), 400

    if protocol in ('icmp', 'any') and (src_port_parts or dst_port_parts):
        return jsonify({"error": "Ports are not allowed with protocol ICMP or ANY"}), 400

    if order is not None:
        try:
            order = int(order)
            if order < 0:
                raise ValueError()
        except ValueError:
            return jsonify({"error": "Order must be a non-negative integer"}), 400

    agent_url = f"http://{peer_ip}:8765/firewall/rules"
    agent_payload = {
        "comment": rule_name,
        "action": action,
        "protocol": protocol,
        "interface": interface,
        "src": src_parts,
        "src_port": src_port_parts,
        "dst": dst_parts,
        "dst_port": dst_port_parts,
        "enabled": True
    }
    if order is not None:
        agent_payload["order"] = order

    try:
        resp = requests.post(agent_url, json=agent_payload, timeout=20)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify({"success": True, "rule_id": 999}), 201
        else:
            try:
                err_data = resp.json()
                error_msg = err_data.get("message") or err_data.get("detail") or resp.text
            except Exception:
                error_msg = resp.text
            raise Exception(error_msg)
    except Exception as e:
        current_app.logger.error(f"Failed to add firewall rule on agent: {e}")
        return jsonify({"error": f"Failed to apply rule on : {str(e)}"}), 502


@client_bp.route('/api/peers/<peer_id>/firewall/rules/<int:rule_id>/toggle', methods=['POST'])
@login_required
def toggle_peer_firewall_rule(peer_id, rule_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    if rule_id < 1 or rule_id > len(live_rules):
        return jsonify({"error": "Rule not found"}), 404

    lr = live_rules[rule_id - 1]
    rule_slug = lr.get("id")
    new_enabled = not lr.get("enabled", True)

    try:
        if new_enabled:
            url = f"http://{peer_ip}:8765/firewall/rules/enable"
        else:
            url = f"http://{peer_ip}:8765/firewall/rules/disable"
            
        payload = {"ids": [rule_slug]}
        resp = requests.post(url, json=payload, timeout=10)
        if resp.ok and resp.json().get("ok"):
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify({"success": True, "enabled": new_enabled}), 200
        else:
            raise Exception("Agent toggle returned failure")
    except Exception as e:
        return jsonify({"error": f"Failed to toggle rule on : {e}"}), 502


@client_bp.route('/api/peers/<peer_id>/firewall/rules/<int:rule_id>', methods=['PUT'])
@login_required
def edit_peer_firewall_rule(peer_id, rule_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    req_data = request.get_json() or {}
    rule_name = req_data.get('rule_name')
    rule_name = rule_name.strip() if rule_name else ''
    
    action = req_data.get('action')
    action = action.lower() if action else 'drop'
    if action == 'accept':
        action = 'allow'
    
    protocol = req_data.get('protocol')
    protocol = protocol.lower() if protocol else 'any'

    interface = req_data.get('interface')
    interface = interface.lower() if interface else 'lan'

    src_ip = req_data.get('src_ip')
    src_ip = src_ip.strip() if (src_ip and isinstance(src_ip, str)) else None

    dst_ip = req_data.get('dst_ip')
    dst_ip = dst_ip.strip() if (dst_ip and isinstance(dst_ip, str)) else None

    src_port = req_data.get('src_port')
    src_port = src_port.strip() if (src_port and isinstance(src_port, str)) else None

    dst_port = req_data.get('dst_port')
    dst_port = dst_port.strip() if (dst_port and isinstance(dst_port, str)) else None

    order = req_data.get('order')

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    if rule_id < 1 or rule_id > len(live_rules):
        return jsonify({"error": "Rule not found"}), 404

    lr = live_rules[rule_id - 1]
    old_slug = lr.get("id")
    rule_order = lr.get("order") if order is None else order

    if not rule_name:
        rule_name = lr.get("comment", "")
        if not rule_name:
            rule_name = f"rule_{random.randint(100000, 999999)}"

    if action not in ('allow', 'drop'):
        return jsonify({"error": "Action must be 'allow' or 'drop'"}), 400

    if protocol not in ('tcp', 'udp', 'tcp+udp', 'icmp', 'any'):
        return jsonify({"error": "Protocol must be 'tcp', 'udp', 'tcp+udp', 'icmp', or 'any'"}), 400

    if interface not in ('lan', 'vpn'):
        return jsonify({"error": "Interface must be 'lan' or 'vpn'"}), 400

    try:
        src_parts = validate_address_spec(src_ip)
    except ValueError as e:
        return jsonify({"error": f"Source Address Error: {str(e)}"}), 400

    try:
        dst_parts = validate_address_spec(dst_ip)
    except ValueError as e:
        return jsonify({"error": f"Destination Address Error: {str(e)}"}), 400

    try:
        src_port_parts = validate_port_spec(src_port)
    except ValueError as e:
        return jsonify({"error": f"Source Port Error: {str(e)}"}), 400

    try:
        dst_port_parts = validate_port_spec(dst_port)
    except ValueError as e:
        return jsonify({"error": f"Destination Port Error: {str(e)}"}), 400

    if protocol in ('icmp', 'any') and (src_port_parts or dst_port_parts):
        return jsonify({"error": "Ports are not allowed with protocol ICMP or ANY"}), 400

    if order is not None:
        try:
            order = int(order)
            if order < 0:
                raise ValueError()
        except ValueError:
            return jsonify({"error": "Order must be a non-negative integer"}), 400

    agent_url = f"http://{peer_ip}:8765/firewall/rules/{old_slug}"
    agent_payload = {
        "comment": rule_name,
        "action": action,
        "protocol": protocol,
        "interface": interface,
        "src": src_parts,
        "src_port": src_port_parts,
        "dst": dst_parts,
        "dst_port": dst_port_parts,
        "enabled": lr.get("enabled", True)
    }
    if rule_order is not None:
        agent_payload["order"] = rule_order

    try:
        resp = requests.put(agent_url, json=agent_payload, timeout=20)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify({"success": True}), 200
        else:
            try:
                err_data = resp.json()
                error_msg = err_data.get("message") or err_data.get("detail") or resp.text
            except Exception:
                error_msg = resp.text
            raise Exception(error_msg)
    except Exception as e:
        current_app.logger.error(f"Failed to edit firewall rule on agent: {e}")
        return jsonify({"error": f"Failed to edit rule on : {str(e)}"}), 502


@client_bp.route('/api/peers/<peer_id>/firewall/rules/<int:rule_id>', methods=['DELETE'])
@login_required
def delete_peer_firewall_rule(peer_id, rule_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    if rule_id < 1 or rule_id > len(live_rules):
        return jsonify({"error": "Rule not found"}), 404

    lr = live_rules[rule_id - 1]
    slug = lr.get("id")

    try:
        url = f"http://{peer_ip}:8765/firewall/rules/remove"
        resp = requests.post(url, json={"ids": [slug]}, timeout=15)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify({"success": True}), 200
        else:
            raise Exception("Agent remove rule returned failure")
    except Exception as e:
        return jsonify({"error": f"Failed to delete rule on : {e}"}), 502


@client_bp.route('/api/peers/<peer_id>/firewall/rules/bulk', methods=['POST'])
@login_required
def bulk_peer_firewall_rules(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    req_data = request.get_json() or {}
    action = req_data.get('action')
    rule_ids = req_data.get('rule_ids')

    if not action or not rule_ids:
        return jsonify({"error": "Invalid payload"}), 400

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    slugs_to_act = []
    for r_id in rule_ids:
        try:
            r_idx = int(r_id) - 1
            if 0 <= r_idx < len(live_rules):
                lr = live_rules[r_idx]
                slug = lr.get("id")
                if slug:
                    slugs_to_act.append(slug)
        except Exception:
            pass

    if not slugs_to_act:
        return jsonify({"error": "No valid rules found to apply action"}), 404

    try:
        if action == 'enable':
            url = f"http://{peer_ip}:8765/firewall/rules/enable"
        elif action == 'disable':
            url = f"http://{peer_ip}:8765/firewall/rules/disable"
        elif action == 'delete':
            url = f"http://{peer_ip}:8765/firewall/rules/remove"
        else:
            return jsonify({"error": "Unsupported action"}), 400

        resp = requests.post(url, json={"ids": slugs_to_act}, timeout=20)
        if resp.ok:
            path = f"/tmp/nbcache_firewall_rules_{peer_id}.json"
            try:
                if os.path.exists(path):
                    os.remove(path)
            except Exception:
                pass
            
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
                
            return jsonify({"success": True}), 200
        else:
            raise Exception(f"Agent bulk {action} returned failure")
    except Exception as e:
        return jsonify({"error": f"Failed to perform bulk {action}: {e}"}), 502


@client_bp.route('/api/peers/<peer_id>/firewall/rules/reorder', methods=['POST'])
@login_required
def reorder_peer_firewall_rules(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    req_data = request.get_json() or {}
    items = req_data.get("items", [])
    if not items:
        return jsonify({"error": "No items provided"}), 400

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    agent_items = []
    for item in items:
        synthetic_id = item.get("id")
        order = item.get("order")
        if 1 <= synthetic_id <= len(live_rules):
            lr = live_rules[synthetic_id - 1]
            agent_items.append({
                "id": lr.get("id"),
                "order": int(order)
            })

    agent_items.sort(key=lambda x: x["order"])
    for idx, item in enumerate(agent_items):
        item["order"] = idx + 1

    agent_url = f"http://{peer_ip}:8765/firewall/rules/reorder"
    try:
        resp = requests.post(agent_url, json={"items": agent_items}, timeout=15)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify(resp.json()), resp.status_code
        return jsonify(resp.json() if resp.headers.get('Content-Type') == 'application/json' else {"error": resp.text}), resp.status_code
    except requests.RequestException as e:
        return jsonify({"error": "Device agent is unreachable"}), 503


@client_bp.route('/api/peers/<peer_id>/firewall/rules/sync', methods=['POST'])
@login_required
def sync_peer_firewall_rules(peer_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
        
    peer_ip = peer.get("ip")
    agent_url = f"http://{peer_ip}:8765/firewall/rules/sync"

    try:
        resp = requests.post(agent_url, timeout=20)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify(resp.json()), resp.status_code
        return jsonify(resp.json() if resp.headers.get('Content-Type') == 'application/json' else {"error": resp.text}), resp.status_code
    except requests.RequestException as e:
        return jsonify({"error": "Device agent is unreachable"}), 503


@client_bp.route('/api/peers/<peer_id>/firewall/rules/<int:rule_id>/reset-counter', methods=['POST'])
@login_required
def reset_peer_firewall_rule_counter(peer_id, rule_id):
    customer_id = session.get('client_customer_id')
    customer = Client.query.get(customer_id) if customer_id else None
    if not customer or not verify_peer_access(customer, peer_id):
        return jsonify({"error": "Unauthorized"}), 403

    peers_data = get_cached_all_netbird_peers(get_api_base_url(), get_api_headers())
    peer = next((p for p in peers_data if p.get("id") == peer_id), None)
    if not peer or not peer.get("ip"):
        return jsonify({"error": " IP not found"}), 404
        
    peer_ip = peer.get("ip")

    try:
        live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
        if not live_resp.ok:
            raise Exception("Failed to fetch live rules")
        live_rules = live_resp.json().get("rules", [])
    except Exception as e:
        return jsonify({"error": f"Device agent is offline or unreachable: {e}"}), 503

    if rule_id < 1 or rule_id > len(live_rules):
        return jsonify({"error": "Rule not found"}), 404

    lr = live_rules[rule_id - 1]
    rule_slug = lr.get("id")
    payload = {"ids": [rule_slug]}
    agent_url = f"http://{peer_ip}:8765/firewall/rules/reset-counter"

    try:
        resp = requests.post(agent_url, json=payload, timeout=15)
        if resp.ok:
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)
            return jsonify(resp.json()), resp.status_code
        return jsonify(resp.json() if resp.headers.get('Content-Type') == 'application/json' else {"error": resp.text}), resp.status_code
    except requests.RequestException as e:
        return jsonify({"error": "Device agent is unreachable"}), 503
