import re
import time
import random
import requests
import logging
from utils.cache_manager import firewall_cache_lock, firewall_rules_cache, firewall_revalidating
from utils.network_validators import validate_address_spec, validate_port_spec
from extensions import db

logger = logging.getLogger(__name__)


class FirewallService:
    @staticmethod
    def get_peer_rules(peer_ip: str, peer_id: str, force_refresh: bool = False) -> tuple:
        """Fetches live agent rules with in-memory caching and parsing."""
        now = time.time()
        cached_live_rules = []
        agent_online = False
        cache_found = False
        cache_time = 0

        with firewall_cache_lock:
            if peer_id in firewall_rules_cache:
                cached_live_rules, agent_online, cache_time = firewall_rules_cache[peer_id]
                cache_found = True

        should_revalidate = force_refresh or not cache_found or (now - cache_time > 15)

        if should_revalidate:
            try:
                url = f"http://{peer_ip}:8765/firewall/rules"
                resp = requests.get(url, timeout=5)
                if resp.ok:
                    agent_online = True
                    cached_live_rules = resp.json().get("rules", [])
                with firewall_cache_lock:
                    firewall_rules_cache[peer_id] = (cached_live_rules, agent_online, time.time())
            except Exception as e:
                logger.error(f"Sync firewall rules fetch failed: {e}")

        rules_data = []
        for idx, lr in enumerate(cached_live_rules):
            src_ips = []
            for s in (lr.get("src") or []):
                if s.startswith('@alias_'):
                    s = '@' + s[7:]
                src_ips.append(s)
            src_ip = ",".join(src_ips) if src_ips else "Any"

            dst_ips = []
            for d in (lr.get("dst") or []):
                if d.startswith('@alias_'):
                    d = '@' + d[7:]
                dst_ips.append(d)
            dst_ip = ",".join(dst_ips) if dst_ips else "Any"

            comment = lr.get("comment", "")
            is_autogenerated = bool(re.match(r"^rule_\d{6}$", comment))
            ui_name = "" if is_autogenerated else comment

            action = lr.get("action", "DROP")
            if action.lower() in ("accept", "allow"):
                action = "ALLOW"
            else:
                action = "DROP"

            src_ports = lr.get("src_port")
            if isinstance(src_ports, list):
                src_port = ",".join(src_ports)
            else:
                src_port = src_ports or ""

            dst_ports = lr.get("dst_port")
            if isinstance(dst_ports, list):
                dst_port = ",".join(dst_ports)
            else:
                dst_port = dst_ports or ""

            rules_data.append({
                "id": idx + 1,
                "rule_name": ui_name,
                "src_ip": src_ip,
                "dst_ip": dst_ip,
                "src_port": src_port,
                "dst_port": dst_port,
                "protocol": lr.get("protocol") or "any",
                "action": action,
                "interface": lr.get("interface") or "lan",
                "enabled": lr.get("enabled", True),
                "active_on_agent": True,
                "direction": lr.get("id"),
                "order": lr.get("order", idx + 1),
                "packets": lr.get("packets"),
                "bytes": lr.get("bytes")
            })

        return rules_data, agent_online

    @staticmethod
    def add_peer_rule(peer_ip: str, peer_id: str, req_data: dict) -> tuple:
        """Validates and adds a firewall rule on the edge device."""
        rule_name = req_data.get('rule_name')
        rule_name = rule_name.strip() if rule_name else ''

        action = req_data.get('action')
        action = action.lower() if action else 'drop'
        if action == 'accept':
            action = 'allow'

        protocol = req_data.get('protocol')
        protocol = protocol.lower() if protocol else 'any'

        interface = req_data.get('interface')
        interface = interface.lower() if interface else 'lan'

        src_ip = req_data.get('src_ip')
        src_ip = src_ip.strip() if (src_ip and isinstance(src_ip, str)) else None

        dst_ip = req_data.get('dst_ip')
        dst_ip = dst_ip.strip() if (dst_ip and isinstance(dst_ip, str)) else None

        src_port = req_data.get('src_port')
        src_port = src_port.strip() if (src_port and isinstance(src_port, str)) else None

        dst_port = req_data.get('dst_port')
        dst_port = dst_port.strip() if (dst_port and isinstance(dst_port, str)) else None

        order = req_data.get('order')

        # Get live rules to generate random default name
        try:
            live_resp = requests.get(f"http://{peer_ip}:8765/firewall/rules", timeout=10)
            live_rules = live_resp.json().get("rules", []) if live_resp.ok else []
        except Exception:
            live_rules = []

        if not rule_name:
            rule_name = f"rule_{random.randint(100000, 999999)}"
            while any(lr.get("comment") == rule_name for lr in live_rules):
                rule_name = f"rule_{random.randint(100000, 999999)}"

        if action not in ('allow', 'drop'):
            return {"error": "Action must be 'allow' or 'drop'"}, 400

        if protocol not in ('tcp', 'udp', 'tcp+udp', 'icmp', 'any'):
            return {"error": "Protocol must be 'tcp', 'udp', 'tcp+udp', 'icmp', or 'any'"}, 400

        if interface not in ('lan', 'vpn'):
            return {"error": "Interface must be 'lan' or 'vpn'"}, 400

        try:
            src_parts = validate_address_spec(src_ip)
        except ValueError as e:
            return {"error": f"Source Address Error: {str(e)}"}, 400

        try:
            dst_parts = validate_address_spec(dst_ip)
        except ValueError as e:
            return {"error": f"Destination Address Error: {str(e)}"}, 400

        try:
            src_port_parts = validate_port_spec(src_port)
        except ValueError as e:
            return {"error": f"Source Port Error: {str(e)}"}, 400

        try:
            dst_port_parts = validate_port_spec(dst_port)
        except ValueError as e:
            return {"error": f"Destination Port Error: {str(e)}"}, 400

        if protocol in ('icmp', 'any') and (src_port_parts or dst_port_parts):
            return {"error": "Ports are not allowed with protocol ICMP or ANY"}, 400

        if order is not None:
            try:
                order = int(order)
                if order < 0:
                    raise ValueError()
            except ValueError:
                return {"error": "Order must be a non-negative integer"}, 400

        agent_url = f"http://{peer_ip}:8765/firewall/rules"
        agent_payload = {
            "comment": rule_name,
            "action": action,
            "protocol": protocol,
            "interface": interface,
            "src": src_parts,
            "src_port": src_port_parts,
            "dst": dst_parts,
            "dst_port": dst_port_parts,
            "enabled": True
        }
        if order is not None:
            agent_payload["order"] = order

        try:
            resp = requests.post(agent_url, json=agent_payload, timeout=15)
            with firewall_cache_lock:
                firewall_rules_cache.pop(peer_id, None)

            if not resp.ok:
                err_data = resp.json() if resp.headers.get("content-type", "").startswith("application/json") else {}
                return {"error": err_data.get("error") or err_data.get("detail") or "Failed to add rule on device"}, resp.status_code

            return resp.json(), resp.status_code
        except requests.RequestException as e:
            return {"error": f"Device agent is offline or unreachable: {e}"}, 503
