"""remove subnet_cidr and mode

Revision ID: 26c050e017a8
Revises: 29e03368e63d
Create Date: 2026-07-22 14:55:05.664757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c050e017a8'
down_revision = '29e03368e63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('mode')
        batch_op.drop_column('subnet_cidr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subnet_cidr', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
