"""create command_logs table

Revision ID: 59f03aaba7ea
Revises: 7e1d37a1b1a6
Create Date: 2026-07-25 18:05:21.062962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59f03aaba7ea'
down_revision = '7e1d37a1b1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('peer_id', sa.String(length=255), nullable=False),
    sa.Column('command_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('command_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_logs_peer_id'), ['peer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_logs_peer_id'))

    op.drop_table('command_logs')
    # ### end Alembic commands ###
