"""create system users table

Revision ID: 90537993a9bd
Revises: dd52cb672eaa
Create Date: 2026-07-14 14:29:21.345665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90537993a9bd'
down_revision = 'dd52cb672eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_users_username'))
        batch_op.drop_index(batch_op.f('ix_system_users_email'))

    op.drop_table('system_users')
    # ### end Alembic commands ###
