"""add_subscription_plans_and_client_lifecycle_fields

Revision ID: d176ccb2b6f1
Revises: a1b2c3d4e5f6
Create Date: 2026-09-08 15:36:53.918644

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'd176ccb2b6f1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create subscription_plans table
    plans_table = op.create_table('subscription_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=False),
        sa.Column('peer_limit', sa.Integer(), nullable=False),
        sa.Column('billing_cycles', sa.String(length=20), nullable=False),
        sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    # 2. Seed initial plans
    op.bulk_insert(plans_table, [
        {
            "name": "starter",
            "display_name": "Starter",
            "peer_limit": 5,
            "billing_cycles": "monthly,yearly",
            "price_monthly": 29.99,
            "price_yearly": 299.99,
            "is_active": True,
            "created_at": datetime.utcnow(),
        },
        {
            "name": "pro",
            "display_name": "Professional",
            "peer_limit": 15,
            "billing_cycles": "monthly,yearly",
            "price_monthly": 79.99,
            "price_yearly": 799.99,
            "is_active": True,
            "created_at": datetime.utcnow(),
        },
        {
            "name": "enterprise",
            "display_name": "Enterprise",
            "peer_limit": 50,
            "billing_cycles": "monthly,yearly",
            "price_monthly": 199.99,
            "price_yearly": 1999.99,
            "is_active": True,
            "created_at": datetime.utcnow(),
        },
    ])

    # 3. Add subscription fields to clients (server_default for existing rows)
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('billing_cycle', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('grace_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('renewal_notified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_clients_plan_id', 'subscription_plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clients_plan_id', type_='foreignkey')
        batch_op.drop_column('renewal_notified_at')
        batch_op.drop_column('grace_expires_at')
        batch_op.drop_column('renewal_date')
        batch_op.drop_column('billing_cycle')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('plan_id')

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###

