"""add_group_peers_table

Revision ID: f0a0a6b4b67c
Revises: 59f03aaba7ea
Create Date: 2026-08-17 13:23:57.978910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a0a6b4b67c'
down_revision = '59f03aaba7ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    # Drop view first to avoid dependency failures during column alterations
    op.execute("DROP VIEW IF EXISTS peer_info;")
    
    if 'group_peers' not in tables:
        op.create_table(
            'group_peers',
            sa.Column('account_id', sa.Text(), nullable=True),
            sa.Column('group_id', sa.String(length=100), nullable=False),
            sa.Column('peer_id', sa.String(length=100), nullable=False),
            sa.Column('adguard_password', sa.String(length=255), nullable=False, server_default='default_password'),
            sa.PrimaryKeyConstraint('group_id', 'peer_id')
        )
    else:
        with op.batch_alter_table('group_peers', schema=None) as batch_op:
            batch_op.alter_column('group_id',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=100),
                   existing_nullable=False)
            batch_op.alter_column('peer_id',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=100),
                   existing_nullable=False)
            
            columns = [c['name'] for c in inspector.get_columns('group_peers')]
            if 'adguard_password' not in columns:
                batch_op.add_column(sa.Column('adguard_password', sa.String(length=255), nullable=False, server_default='default_password'))
            if 'account_id' not in columns:
                batch_op.add_column(sa.Column('account_id', sa.Text(), nullable=True))

    # Create or replace the view
    op.execute("CREATE OR REPLACE VIEW peer_info AS SELECT group_id, peer_id, adguard_password FROM group_peers;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop view first
    op.execute("DROP VIEW IF EXISTS peer_info;")
    # Drop table
    op.drop_table('group_peers')
    # ### end Alembic commands ###
